// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcJqoxOSXWN9fxX3_xh3FHZ45_9zXG8qo',
    appId: '1:685363770690:web:fc797c89f7090619ee04db',
    messagingSenderId: '685363770690',
    projectId: 'recipes-app-5b76f',
    authDomain: 'recipes-app-5b76f.firebaseapp.com',
    storageBucket: 'recipes-app-5b76f.firebasestorage.app',
    measurementId: 'G-83JCSEMZK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC40ClsKmPxk1BGwJSwCE2dvtsyzvZ9qK8',
    appId: '1:685363770690:android:e4290d8fd3ffb285ee04db',
    messagingSenderId: '685363770690',
    projectId: 'recipes-app-5b76f',
    storageBucket: 'recipes-app-5b76f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAafZKQAqDcwXsZnGjfFxX3Pa7nTTYqF2k',
    appId: '1:685363770690:ios:d0d34b7e64c2a57fee04db',
    messagingSenderId: '685363770690',
    projectId: 'recipes-app-5b76f',
    storageBucket: 'recipes-app-5b76f.firebasestorage.app',
    iosBundleId: 'com.example.recipesApp',
  );
}
